require("config.settings")
-- require("config.custom_functions")
-- require("config.rust")
require("config.helpers")
require("config.globals")
require("config.user_commands")
require("config.lazy")
require("config.mappings")
require("config.auto_commands")
